# This is a basic workflow to help you get started with Actions

name: Build pdf

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 12 1 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: cd on workspace
        run: cd $GITHUB_WORKSPACE


      - name: LaTeX compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@259e5ff953ad4d4616fbd09cc87a526ee5c4499a
        uses: dante-ev/latex-action@v0.2.0
        with:
          # The root LaTeX file to be compiled
          root_file: sample.tex
          # The working directory for the latex compiler to be invoked
          working_directory: . # optional
          # LaTeX engine to be used
          compiler: pdflatex # optional, default is latexmk
          # Extra arguments to be passed to the latex compiler
          args: ""
          # Install extra packages by apt-get
          # extra_system_packages: # optional


      - name: Latex Biber Action
        # You may pin to the exact commit or the version.
        # uses: julianahrens/latex-biber-action@b030657c4bc77278ee7ec178a6a4339e50c6333b
        uses: julianahrens/latex-biber-action@v2
        with:
          # Filename of .tex file
          filename: sample
          # Define build directory
          output-directory: .
          
      - name: LaTeX compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@259e5ff953ad4d4616fbd09cc87a526ee5c4499a
        uses: dante-ev/latex-action@v0.2.0
        with:
          # The root LaTeX file to be compiled
          root_file: sample.tex
          # The working directory for the latex compiler to be invoked
          working_directory: . # optional
          # LaTeX engine to be used
          compiler: pdflatex # optional, default is latexmk
          # Extra arguments to be passed to the latex compiler
          args: ""
          # Install extra packages by apt-get
          # extra_system_packages: # optional
                        
      - name: Rename pdf
        run: mv sample.pdf cv.pdf
      
      - name: Create empty changelog
        run: echo "# Update CV" > CHANGELOG.md
        
      - name: Update Release
        # You may pin to the exact commit or the version.
        # uses: johnwbyrd/update-release@1d5ec4791e40507e5eca3b4dbf90f0b27e7e4979
        uses: johnwbyrd/update-release@v1.0.0
        with:
          # Your Github token; try \$\{\{ secrets.GITHUB_TOKEN \}\} if your build lasts less than an hour, or create your own secret token with repository access if your build requires longer than an hour.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Paths to built files to be released. May be absolute or relative to \$\{\{ github.workspace \}\}.
          files: cv.pdf
          # The name of the release to be created. A reasonable looking release name will be created from the current \$\{\{ github.ref \}\} if this input is not supplied.
          # release: # optional
          # The name of the tag to be used. If not provided, the name of the release will be used.
          tag: "latest" # optional
          # A one-line description for both the tag and the release.
          message: "Update CS" # optional
          # A fuller description of the release.
          #body: # optional
          # Should the release, if created, be marked as a prerelease?  Such releases are generally publicly visible.
          # prerelease: # optional, default is true
          # Should the release, if created, be marked as a draft?  Such releases are generally not publicly visible.
          # draft: # optional
